CREATE TABLE IF NOT EXISTS cards (
	id SERIAL PRIMARY KEY,
	index SMALLINT NOT NULL,
	body VARCHAR(100) NOT NULL,
	color SMALLINT,
    status SMALLINT,
	game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE
);